### ISSUE TITLE
SQlite error if no column name "name"

### ISSUE THREAD

**Issue by Sparo** [DalerLeo/strapi-plugin-prev-next-button#1]
Hi,

tnx for the plugin.

I have tried to install this plugin, but there was an Error when I open edit view of the content type.
Problem is sqlite error that says that there is no required column name.
```
SqliteError: 

select `t0`.`id`, `t0`.`name` 
from `TABLE_NAME` as `t0` 
where ((`t0`.`locale` = 'en' and `t0`.`id` > '117449')) 
order by `t0`.`id` asc limit 1 

- no such column: t0.name
```
I do not use such column name so I would love to not to be forced to use it.

I have looked through the code and I have seen that at the server part in the service file you are using following code:

**node_modules/strapi-plugin-prev-next-button/server/services/prev-next-items.ts**
```
    const next = await strapi.entityService.findMany(uid, {
      fields: ['id', 'name'], // =============== > this is forcing "name" column name
      filters: { id: { $gt: id } },
      sort: {id: 'asc'},
      limit: 1,
    });
    const prev = await strapi.entityService.findMany(uid, {
      fields: ['id', 'name'], // =============== > this is forcing "name" column name
      filters: { id: { $lt: id } },
      sort: {id: 'desc'},
      limit: 1,
    });
```

I assume that this line is making problems.

Is there something we can do to fix this?

Tnx,
Nenad

**Comment by DalerLeo** [comment]
Hi @Sparo , 
Thanks for reaching out and describing your issue in detail.

I Will try to fix it today.
Thanks
