### ISSUE TITLE
Request: option to select which field prev/next is based on

### ISSUE THREAD

**Issue by tennox** [DalerLeo/strapi-plugin-prev-next-button#3]
Thanks for this! :heart: 

Awesome addition:
Ability to select which field to order by when selecting prev/next - we have internal IDs/dates that the logical ordering makes much more sense in, not the internal Strapi ID :tipping_hand_man:

**Comment by YCPyc** [comment]
Second the request. In our project, for example, we have 2 collections: modules and skills. Each module has many skills. Based on the way we import the skills, they are not incremented up based on the module they belong to. So a good ordering here would be showing the skills by both id and the module relation.

**Comment by DalerLeo** [comment]
Hey @tennox and @YCPyc, thank you both for your feedback and kind words! ❤️

I understand the need for better ordering logic.
I am planning to work on it coming weekend.

**Comment by DalerLeo** [comment]
Hey @tennox  & @YCPyc, please take a look the MR #4 description and let me know if it covers your case at least partially.

**Comment by tennox** [comment]
Yes that's great for us, thanks ❣️
